[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.injective-mainnet]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams", details = { type = "substreams", url = "https://mainnet.injective.streamingfast.io:443", token = "eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwMTUxODA2MTAsImp0aSI6IjJjNDFmZGNjLTI0MTAtNDczYi04MzAxLTg4YzAxZWIwNzkzOSIsImlhdCI6MTY5OTgyMDYxMCwiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIwcWVydTJiZDI4Yjk1NGEzNWMxMmUiLCJ2IjoxLCJha2kiOiJjMWZiM2Y0ODBjOTliZTMwZGY5OWY4YjgyMWNkNzFkNDhmZTk5N2ExMGUxMTZkMDNlM2M4NmQ2OGIzMDc0ZjUxIiwidWlkIjoiMHFlcnUyYmQyOGI5NTRhMzVjMTJlIn0.Ywfmu7xiUiQalEmhZT3UXddhmOGUIOtufnQUo0FabNBr_fQ7ZH5nGTcPUrZAtAJAXeWqvYtGstoRbytoXyarKA", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]